// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const  calendarEvents = [
   {
    title: "Math",
    allDay: false,
    start: new Date(2025, 5, 30, 8, 0),
    end: new Date(2025, 5, 30, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 5, 30, 9, 0),
    end: new Date(2025, 5, 30, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 5, 30, 10, 0),
    end: new Date(2025, 5, 30, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 5, 30, 11, 0),
    end: new Date(2025, 5, 30, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 5, 30, 13, 0),
    end: new Date(2025, 5, 30, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 5, 30, 14, 0),
    end: new Date(2025, 5, 30, 14, 45),
  },

  // Tuesday, July 1
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 1, 9, 0),
    end: new Date(2025, 6, 1, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 1, 10, 0),
    end: new Date(2025, 6, 1, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 1, 11, 0),
    end: new Date(2025, 6, 1, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 1, 14, 0),
    end: new Date(2025, 6, 1, 14, 45),
  },

  // Wednesday, July 2
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 2, 8, 0),
    end: new Date(2025, 6, 2, 8, 45),
  },

  // Thursday, July 3
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 3, 13, 0),
    end: new Date(2025, 6, 3, 13, 45),
  },

  // Friday, July 4
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 4, 14, 0),
    end: new Date(2025, 6, 4, 14, 45),
  },
];

export const lessonsData = [

		{ id: 1, name: "Mathematics", class: "Grade 6", teacher: "Mr. Johnson" },
	{ id: 2, name: "English Language", class: "Grade 5", teacher: "Ms. Smith" },
	{ id: 3, name: "Basic Science", class: "Grade 4", teacher: "Mrs. Ahmed" },
	{ id: 4, name: "Social Studies", class: "Grade 6", teacher: "Mr. Brown" },
	{ id: 5, name: "Computer Studies", class: "Grade 3", teacher: "Miss Clara" },
	{ id: 6, name: "Creative Arts", class: "Grade 2", teacher: "Mr. Daniels" },
	{ id: 7, name: "Civic Education", class: "Grade 5", teacher: "Mrs. Okoro" },
	{ id: 8, name: "Physical Education", class: "Grade 1", teacher: "Coach Mark" },
	{ id: 9, name: "Health Education", class: "Grade 3", teacher: "Ms. Linda" },
	{ id: 10, name: "Religious Studies", class: "Grade 4", teacher: "Mr. Emmanuel" },

]
export const examsData = [
	{
		id: 1,
		name: "Mathematics",
		class: "Grade 6",
		teacher: "Mr. Johnson",
		date: "2025-07-15",
	},
	{
		id: 2,
		name: "English Language",
		class: "Grade 5",
		teacher: "Ms. Smith",
		date: "2025-07-16",
	},
	{
		id: 3,
		name: "Basic Science",
		class: "Grade 4",
		teacher: "Mrs. Ahmed",
		date: "2025-07-17",
	},
	{
		id: 4,
		name: "Social Studies",
		class: "Grade 6",
		teacher: "Mr. Brown",
		date: "2025-07-18",
	},
	{
		id: 5,
		name: "Computer Studies",
		class: "Grade 3",
		teacher: "Miss Clara",
		date: "2025-07-19",
	},
	{
		id: 6,
		name: "Creative Arts",
		class: "Grade 2",
		teacher: "Mr. Daniels",
		date: "2025-07-20",
	},
	{
		id: 7,
		name: "Civic Education",
		class: "Grade 5",
		teacher: "Mrs. Okoro",
		date: "2025-07-21",
	},
	{
		id: 8,
		name: "Physical Education",
		class: "Grade 1",
		teacher: "Coach Mark",
		date: "2025-07-22",
	},
	{
		id: 9,
		name: "Health Education",
		class: "Grade 3",
		teacher: "Ms. Linda",
		date: "2025-07-23",
	},
	{
		id: 10,
		name: "Religious Studies",
		class: "Grade 4",
		teacher: "Mr. Emmanuel",
		date: "2025-07-24",
	},
];

 export const assignmentsData = [
	{
		id: 1,
		name: "Math Assignment 1",
		class: "Grade 6",
		teacher: "Mr. Johnson",
		dueDate: "2025-07-12",
	},
	{
		id: 2,
		name: "English Comprehension",
		class: "Grade 5",
		teacher: "Ms. Smith",
		dueDate: "2025-07-13",
	},
	{
		id: 3,
		name: "Science Experiment Report",
		class: "Grade 4",
		teacher: "Mrs. Ahmed",
		dueDate: "2025-07-14",
	},
	{
		id: 4,
		name: "Social Studies Worksheet",
		class: "Grade 6",
		teacher: "Mr. Brown",
		dueDate: "2025-07-15",
	},
	{
		id: 5,
		name: "Computer Project – My First Program",
		class: "Grade 3",
		teacher: "Miss Clara",
		dueDate: "2025-07-16",
	},
	{
		id: 6,
		name: "Art Assignment – My Family",
		class: "Grade 2",
		teacher: "Mr. Daniels",
		dueDate: "2025-07-17",
	},
	{
		id: 7,
		name: "Civic Education Essay",
		class: "Grade 5",
		teacher: "Mrs. Okoro",
		dueDate: "2025-07-18",
	},
	{
		id: 8,
		name: "P.E. Practice Journal",
		class: "Grade 1",
		teacher: "Coach Mark",
		dueDate: "2025-07-19",
	},
	{
		id: 9,
		name: "Health Education Notes",
		class: "Grade 3",
		teacher: "Ms. Linda",
		dueDate: "2025-07-20",
	},
	{
		id: 10,
		name: "Religious Studies Quiz Prep",
		class: "Grade 4",
		teacher: "Mr. Emmanuel",
		dueDate: "2025-07-21",
	},
];

export const resultsData = [
	{
		id: 1,
		name: "Mathematics",
		student: "Tolu Adebayo",
		score: 85,
		teacher: "Mr. Johnson",
		type: "exam",
		date: "2025-07-01",
		class: "Grade 6",
	},
	{
		id: 2,
		name: "English Language",
		student: "Grace Nwosu",
		score: 92,
		teacher: "Ms. Smith",
		type: "assignment",
		date: "2025-07-03",
		class: "Grade 5",
	},
	{
		id: 3,
		name: "Basic Science",
		student: "Samuel Okoro",
		score: 74,
		teacher: "Mrs. Ahmed",
		type: "exam",
		date: "2025-07-02",
		class: "Grade 4",
	},
	{
		id: 4,
		name: "Social Studies",
		student: "Fatima Bello",
		score: 88,
		teacher: "Mr. Brown",
		type: "assignment",
		date: "2025-07-04",
		class: "Grade 6",
	},
	{
		id: 5,
		name: "Computer Studies",
		student: "David Uche",
		score: 95,
		teacher: "Miss Clara",
		type: "exam",
		date: "2025-07-05",
		class: "Grade 3",
	},
	{
		id: 6,
		name: "Creative Arts",
		student: "Esther Musa",
		score: 90,
		teacher: "Mr. Daniels",
		type: "assignment",
		date: "2025-07-06",
		class: "Grade 2",
	},
	{
		id: 7,
		name: "Civic Education",
		student: "Michael Ade",
		score: 81,
		teacher: "Mrs. Okoro",
		type: "exam",
		date: "2025-07-07",
		class: "Grade 5",
	},
	{
		id: 8,
		name: "Physical Education",
		student: "Peace Ojo",
		score: 78,
		teacher: "Coach Mark",
		type: "assignment",
		date: "2025-07-08",
		class: "Grade 1",
	},
	{
		id: 9,
		name: "Health Education",
		student: "Daniel Eze",
		score: 84,
		teacher: "Ms. Linda",
		type: "exam",
		date: "2025-07-09",
		class: "Grade 3",
	},
	{
		id: 10,
		name: "Religious Studies",
		student: "Aisha Lawal",
		score: 91,
		teacher: "Mr. Emmanuel",
		type: "assignment",
		date: "2025-07-10",
		class: "Grade 4",
	},
];


export const eventsData = [
	{
		id: 1,
		name: "Mathematics Quiz Competition",
		class: "Grade 6",
		date: "2025-07-15",
		startTime: "09:00 AM",
		endTime: "10:30 AM",
	},
	{
		id: 2,
		name: "English Spelling Bee",
		class: "Grade 5",
		date: "2025-07-16",
		startTime: "11:00 AM",
		endTime: "12:00 PM",
	},
	{
		id: 3,
		name: "Science Fair",
		class: "Grade 4",
		date: "2025-07-17",
		startTime: "10:00 AM",
		endTime: "01:00 PM",
	},
	{
		id: 4,
		name: "Cultural Day",
		class: "All Classes",
		date: "2025-07-18",
		startTime: "09:00 AM",
		endTime: "02:00 PM",
	},
	{
		id: 5,
		name: "Career Talk",
		class: "Grade 6",
		date: "2025-07-19",
		startTime: "01:00 PM",
		endTime: "02:30 PM",
	},
	{
		id: 6,
		name: "Health Awareness Program",
		class: "Grade 3",
		date: "2025-07-20",
		startTime: "10:30 AM",
		endTime: "12:00 PM",
	},
	{
		id: 7,
		name: "Inter-class Debate",
		class: "Grade 5 & 6",
		date: "2025-07-21",
		startTime: "12:00 PM",
		endTime: "01:30 PM",
	},
	{
		id: 8,
		name: "Art Exhibition",
		class: "Grade 2",
		date: "2025-07-22",
		startTime: "11:30 AM",
		endTime: "12:30 PM",
	},
	{
		id: 9,
		name: "PTA Meeting",
		class: "All Classes",
		date: "2025-07-23",
		startTime: "09:00 AM",
		endTime: "11:00 AM",
	},
	{
		id: 10,
		name: "School Sports Day",
		class: "All Classes",
		date: "2025-07-24",
		startTime: "08:00 AM",
		endTime: "01:00 PM",
	},
];

export const announcementsData = [
	{
		id: 1,
		name: "Mid-Term Break Begins Friday",
		class: "All Classes",
		date: "2025-07-10",
	},
	{
		id: 2,
		name: "Project Submissions Due",
		class: "Grade 5",
		date: "2025-07-12",
	},
	{
		id: 3,
		name: "Parent-Teacher Conference",
		class: "Grade 6",
		date: "2025-07-13",
	},
	{
		id: 4,
		name: "Library Closed for Renovation",
		class: "All Classes",
		date: "2025-07-14",
	},
	{
		id: 5,
		name: "Sportswear Day - Come in Sports Kit",
		class: "Grade 3 & 4",
		date: "2025-07-15",
	},
	{
		id: 6,
		name: "School Fees Reminder",
		class: "All Classes",
		date: "2025-07-16",
	},
	{
		id: 7,
		name: "Inter-House Sports Registration",
		class: "Grade 4 – 6",
		date: "2025-07-17",
	},
	{
		id: 8,
		name: "Creative Arts Exhibition Opening",
		class: "Grade 2",
		date: "2025-07-18",
	},
	{
		id: 9,
		name: "Weekly Quiz Coming Monday",
		class: "Grade 5",
		date: "2025-07-19",
	},
	{
		id: 10,
		name: "New Uniform Policy Effective",
		class: "All Classes",
		date: "2025-07-20",
	},
];
